/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kargo9;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author op
 */
public class EklePaket extends javax.swing.JFrame {

    /**
     * Creates new form eklePaket
     */
    public EklePaket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ekleButton = new javax.swing.JButton();
        gAdText = new javax.swing.JTextField();
        aAdText = new javax.swing.JTextField();
        gSehirText = new javax.swing.JTextField();
        aSehirText = new javax.swing.JTextField();
        boyText = new javax.swing.JTextField();
        agirlikText = new javax.swing.JTextField();
        genislikText = new javax.swing.JTextField();
        fiyatLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hataLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cikisButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ekleButton.setText("Paketi Ekle");
        ekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleButtonActionPerformed(evt);
            }
        });

        gAdText.setText("Gönderici Kullanıcı");

        aAdText.setText("Alıcı Kullanıcı");

        gSehirText.setText("Gönderici Şehir");

        aSehirText.setText("Alıcı Şehir");

        boyText.setText("Boy");

        agirlikText.setText("Ağırlık");
        agirlikText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agirlikTextActionPerformed(evt);
            }
        });

        genislikText.setText("Genişlik");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Paket Ekle");

        jButton1.setText("Fiyat Hesaplat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cikisButton.setText("Çıkış");
        cikisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gSehirText)
                    .addComponent(gAdText)
                    .addComponent(boyText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(genislikText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(aAdText, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addComponent(aSehirText))
                    .addComponent(agirlikText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(fiyatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ekleButton)
                .addGap(17, 17, 17)
                .addComponent(cikisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gAdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aAdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gSehirText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aSehirText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(hataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genislikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agirlikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(fiyatLabel))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cikisButton)
                    .addComponent(ekleButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agirlikTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agirlikTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agirlikTextActionPerformed

    private void ekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleButtonActionPerformed
        // Form bilgileri:
        hataLabel.setText("");
        String gUsername = gAdText.getText();
        String gSehir = gSehirText.getText();
        String aUsername = aAdText.getText();
        String aSehir = aSehirText.getText();
        //Boyutlar
        int boy = 0;
        int genislik = 0;
        int agirlik = 0;
        try{
            boy = Integer.parseInt(boyText.getText());
            genislik = Integer.parseInt(genislikText.getText());
            agirlik = Integer.parseInt(agirlikText.getText());
        }catch(Exception e){
            hataLabel.setText("Boy,genislik ve agirlik sadece sayı olmalı.");
        }
        //IDler
        int paketID = Aletler.sonEklenenID("paket") + 1;
        ArrayList<String[]> gIDQ = null;
        ArrayList<String[]> aIDQ = null;
        gIDQ = Aletler.findSatir(Aletler.getKullanicilar(), 1, gUsername);
        aIDQ = Aletler.findSatir(Aletler.getKullanicilar(), 1, aUsername);
        if (gIDQ.isEmpty() || !gIDQ.get(0)[1].equals(gUsername)){
            hataLabel.setText("Gönderen kullanıcı bulunamadı");
        }else if(aIDQ.isEmpty() || !aIDQ.get(0)[1].equals(aUsername)){
            hataLabel.setText("Gönderen alıcı bulunamadı");
        }else{
            try {
                //Girdiler doğru
                //Paket Ekle
                //Şimdilik Satır ekleme olsun
                Aletler.ekleSatirPaketler(
                        paketID + " " + aIDQ.get(0)[0] + " " + aIDQ.get(0)[0] +
                        " " + aSehir + " " + gSehir + " " + boy + " " + genislik
                        + " " + agirlik
                );
                hataLabel.setText("Paket eklendi");
            } catch (IOException ex) {
                hataLabel.setText("Veritabanı hata");
            }
        }
  
        

    }//GEN-LAST:event_ekleButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        hataLabel.setText("");
        int boy = 0;
        int genislik = 0;
        int agirlik= 0;
        try{
            boy = Integer.parseInt(boyText.getText());
            genislik = Integer.parseInt(genislikText.getText());
            agirlik = Integer.parseInt(agirlikText.getText());
        }catch(Exception e){
            hataLabel.setText("Boy,genislik ve agirlik sadece sayı olmalı.");
        }
        fiyatLabel.setText((((boy * genislik * agirlik) / 1000) + 1) + " TL");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cikisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cikisButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EklePaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EklePaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EklePaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EklePaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EklePaket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aAdText;
    private javax.swing.JTextField aSehirText;
    private javax.swing.JTextField agirlikText;
    private javax.swing.JTextField boyText;
    private javax.swing.JButton cikisButton;
    private javax.swing.JButton ekleButton;
    private javax.swing.JLabel fiyatLabel;
    private javax.swing.JTextField gAdText;
    private javax.swing.JTextField gSehirText;
    private javax.swing.JTextField genislikText;
    private javax.swing.JLabel hataLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
